#!/usr/bin/env python3

s = "CTTCACAACAGAGGTTATGGTTATGTCTTTAACCGCGCGCTCAGGGGAGACGCCCTGTGGTTTCTCAGAGCTTACACAATTGCGCTCTAAGGGTGCGGTCTAACGCGATATTATGCTTCGAGGGTTTCTGGGAAGCTCTTCGTACGTCTTGTCCCACGGTGCGGAACACGGAATACGGCCTCGGCAACTTTATAGTCAGATTGTATAGGCTCGCATTGTAGGGAAGATCTCTTCCTAAGGAGTCTAAATGTGGAGCACCATGTAAAGAGTTATGACGCCGTCAGGTCCATATCGCGAGCTTAACACCCATCTAGTCTCGAGTGGACCAGATTAACGTTATCTCTGTACTTCGTGCTCATCGAGGACTATCAGCCTAAAACACGCCGGGATAATATCCTCTAGTACCCTCGAACACCAAAGTGTTTCGCTGATGACGGTTCTCCTGTACTTCTTGCAAGAGCTTTCGAGCGTGGACAAGGGTCATTCTCAGCGATGGTCCAGTAGCCGGTGCTACGGCGGCTGTCTATTGCAAAGAGCGAACTTCTCTTCAAGACAGCTACCCCTGCCCATCGTACTAGATATTGTAAGTCGCAAACGGTGAAAGAAGACATATAATCGCTGTTGAAATATCTCTGGGAACGCGGTTCGCCTAACCCCCCACCAGCTCAAGGCGATAAACACGACTTCAGGGTCTGAGGATAATTCACAGTAGTCTGTTACTCCGAAAGTGGCATGCATAGGTGCCACGTCTGAGCACATGCTACCAGAGGAGGTCATATTACGCGGCGGGCGAGCTATTGGAACGAAAAAAGGAGCCGTCCCAGTAGCGGACCAATTAAAAAGTGTTATCTGTGCCTGGTTTGGAGGGTTAAGACTTTGAAAAAACCCTACTAACGCACCTTTGCTACGTTTACATGCGACT"

def rc(dna):
    rs = s[::-1]
    rs = rs.replace("A", "t")
    rs = rs.replace("C", "g")
    rs = rs.replace("T", "a")
    rs = rs.replace("G", "c")
    print(rs.upper())

rc(s)
